In [8]:
import numpy as np
import matplotlib.pyplot as plt
def limit(c, n=25, p=2):
    z = 0
    for i in range(1, n):
        z = z**p + c
        if np.abs(z) > 2:
            return np.inf
    return np.abs(z)

In [9]:
def mandelbrot(n=25, size=250, xlim=(-2,2), ylim=(-2,2), p=2):
    x = np.linspace(xlim[0], xlim[1], size)
    y = np.linspace(ylim[0], ylim[1], size)
    m = np.zeros((size, size))
    for i in range(size):
        for j in range(size):
            z = limit(x[i] + y[j]*1j, n, p)
            if z < 2:
                m[j,i] = 1
    return m

In [10]:
def mandelbrot_color(n=25, size=250, xlim=(-2,2), ylim=(-2,2), p=2):
    x = np.linspace(xlim[0], xlim[1], size)
    y = np.linspace(ylim[0], ylim[1], size)
    m = np.zeros((size, size))
    for i in range(size):
        for j in range(size):
            c = x[i] + y[j]*1j
            z = 0
            for k in range(n):
                z = z**p + c
                if np.abs(z) < 2:
                    m[j,i] += 1
                else:
                    break
    return m

In [11]:
limit(1)
mandelbrot()
mandelbrot_color()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
mu = 100
sigma = 15
x = mu + sigma*np.random.randn(10000)
plt.hist(x, 50, normed=1, facecolor="g", alpha=0.75)
plt.title("Histogram of IQ")
plt.xlabel("Smarts")
plt.ylabel("Probability")
plt.axis([40, 160, 0, 0.03])
plt.grid(True)
plt.show()

In [2]:
#导入 numpy
import numpy as np 
#创建两个数组 
a=np.array([[1,2,3],[4,5,6],[11,12,13],[14,15,16]]) 
print('axis=0 垂直方向 平均分隔') 
r=np.split(a,2,axis=0) 
print(r[0]) 
print(r[1]) 
print('axis=1 水平方向 按位置分隔') 
r=np.split(a,[2],axis=1) 
print(r)
print(r[0]) 
print(r[1]) 

axis=0 垂直方向 平均分隔
[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]
axis=1 水平方向 按位置分隔
[array([[ 1,  2],
       [ 4,  5],
       [11, 12],
       [14, 15]]), array([[ 3],
       [ 6],
       [13],
       [16]])]
[[ 1  2]
 [ 4  5]
 [11 12]
 [14 15]]
[[ 3]
 [ 6]
 [13]
 [16]]


In [5]:
arr1 = np.array([[0,1,2,3]]) 
print(arr1.shape )
# (4, 1) 

arr2 = np.array([1,2,3]) 
arr2.shape 
# (3,) 
arr1+arr2 



(1, 4)


ValueError: operands could not be broadcast together with shapes (1,4) (3,) 